- name: Setup my desktop
  hosts: localhost
  vars:
    nvim_version: stable

  pre_tasks:
    - name: Update Apt
      when: ansible_os_family == "Debian"
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present

  tasks:
    - name: Install tools
      ansible.builtin.include_tasks: tasks/tools.yaml
      tags:
        - tools
        - dotfiles

    - name: Install gui
      ansible.builtin.include_tasks: tasks/gui.yaml
      tags:
        - gui
        - desktop

    - name: Install neomvim
      ansible.builtin.include_tasks: tasks/neovim.yaml
      tags:
        - neovim
        - nvim

    - name: Install alacritty
      ansible.builtin.include_tasks: tasks/alacritty.yaml
      tags:
        - alacritty

    - name: Install dotfiles
      ansible.builtin.include_tasks: tasks/my-dotfiles.yaml
      tags:
        - dotfiles
