- name: Install dependancies on apt
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      [
        "cmake",
        "pkg-config",
        "libfreetype6-dev",
        "libfontconfig1-dev",
        "libxcb-xfixes0-dev",
        "libxkbcommon-dev",
        "python3",
      ]
- name: Install dependancies on dnf
  become: true
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name:
      [
        "cmake",
        "freetype-devel",
        "fontconfig-devel",
        "libxcb-devel",
        "libxkbcommon-devel",
        "g++",
      ]

- name: Git clone the alacritty repo
  ansible.builtin.git:
    dest: /tmp/alacritty
    repo: https://github.com/alacritty/alacritty.git

- name: Build and install Alacritty
  environment:
    PATH: ~/.cargo/bin:{{ ansible_env.PATH }}
  ansible.builtin.shell: |
    cd /tmp/alacritty
    rustup override set stable
    rustup update stable
    cargo build --release
  register: command_results
  changed_when: command_results.rc == 0

- name: Install Alacritty
  become: true
  ansible.builtin.copy:
    src: /tmp/alacritty/target/release/alacritty
    dest: /usr/local/bin
    mode: "751"

- name: Remove the tmp folder
  ansible.builtin.file:
    state: absent
    path: /tmp/alacritty/
