- name: Install brave-browser repo on debian like os's
  become: true
  when: ansible_os_family == "Debian"
  block:
    - name: Download key
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        mode: u=rw,g=r,o=r
    - name: Add repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
        state: present

- name: Install brave-browser on RedHat like os's
  become: true
  when: ansible_os_family == "RedHat"
  block:
    - name: Install dn-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
    - name: Import rpm-key
      ansible.builtin.rpm_key:
        key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    - name: Add brave-browser rpm repo
      ansible.builtin.get_url:
        url: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        dest: /etc/yum.repos.d/brave-browser.repo
        mode: u=rw,g=r,o=r

- name: Install gui for apt
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    update_cache: true
    name:
      [
        "i3-wm",
        "pavucontrol",
        "i3lock",
        "i3lock-fancy",
        "picom",
        "feh",
        "rofi",
        "polybar",
        "dunst",
        "arandr",
        "autorandr",
        "xdotool",
        "blueman",
        "xbindkeys",
        "redshift",
        "xclip",
        "flameshot",
        "brave-browser",
        "brightnessctl",
      ]

- name: Install gui for pacman
  become: true
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name:
      [
        "unzip",
        "i3-wm",
        "pavucontrol",
        "i3lock",
        "picom",
        "feh",
        "rofi",
        "polybar",
        "dunst",
        "arandr",
        "autorandr",
        "xdotool",
        "blueman",
        "xbindkeys",
        "redshift",
        "xclip",
        "flameshot",
        "brightnessctl",
        "lightdm",
        "lightdm-gtk-greeter",
        "bluez",
        "bluez-utils",
      ]
- name: Enable lightdm on arch distros
  become: true
  when: ansible_os_family == "Archlinux"
  ansible.builtin.systemd:
    name: lightdm
    enabled: true
    state: stopped

- name: Install gui for dnf
  become: true
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name:
      [
        "i3",
        "i3lock",
        "picom",
        "pavucontrol",
        "feh",
        "rofi",
        "polybar",
        "dunst",
        "arandr",
        "autorandr",
        "xdotool",
        "blueman",
        "xbindkeys",
        "redshift",
        "xclip",
        "flameshot",
        "brave-browser",
        "brightnessctl",
      ]

- name: Install i3lock-fancy on dnf
  when: ansible_os_family == "RedHat" or ansible_os_family == "Archlinux"
  block:
    - name: Clone i3lock-fancy repo
      ansible.builtin.git:
        repo: https://github.com/meskarune/i3lock-fancy.git
        dest: /tmp/i3lock_fancy

    - name: Install i3lock-fancy
      become: true
      register: result
      changed_when: result.rc == 0
      ansible.builtin.shell: |
        cd /tmp/i3lock_fancy
        make install

- name: Switch to pulseaudio on fedora
  when: ansible_os_family == "RedHat"
  register: result
  changed_when: "'Installed' in result.stdout"
  become: true
  ansible.builtin.command: dnf -y swap --allowerasing pipewire-pulseaudio pulseaudio

- name: Download greenclip
  become: true
  ansible.builtin.get_url:
    url: https://github.com/erebe/greenclip/releases/download/v4.2/greenclip
    dest: /usr/local/bin/
    mode: u=rwx,g=rx,o=rx

- name: "Install fonts"
  block:
    - name: Ensure fonts folder exists
      ansible.builtin.file:
        path: ~/.fonts
        state: directory
        mode: "775"

    - name: Install jetbrains mono
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip
        dest: ~/.fonts
        remote_src: true

    - name: Reset font cache
      ansible.builtin.command: fc-cache -fv
      register: result
      changed_when: result.rc == 0
