- name: Install gui for apt
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      [
        "i3-wm",
        "pavucontrol",
        "i3lock",
        "i3lock-fancy",
        "picom",
        "feh",
        "rofi",
        "polybar",
        "dunst",
        "arandr",
        "autorandr",
        "xdotool",
        "blueman",
        "xbindkeys",
        "redshift",
        "xclip",
      ]

- name: Install gui for dnf
  become: true
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name:
      [
        "i3",
        "i3lock",
        "picom",
        "pavucontrol",
        "feh",
        "rofi",
        "polybar",
        "dunst",
        "arandr",
        "autorandr",
        "xdotool",
        "blueman",
        "xbindkeys",
        "redshift",
        "xclip",
      ]

- name: Install i3lock-fancy on dnf
  when: ansible_os_family == "RedHat"
  block:
    - name: Clone i3lock-fancy repo
      ansible.builtin.git:
        repo: https://github.com/meskarune/i3lock-fancy.git
        dest: /tmp/i3lock_fancy

    - name: Install i3lock-fancy
      become: true
      register: result
      changed_when: result.rc == 0
      ansible.builtin.shell: |
        cd /tmp/i3lock_fancy
        make install

- name: Switch to pulseaudio on fedora
  when: ansible_os_family == "RedHat"
  register: result
  changed_when: "'Installed' in result.stdout"
  become: true
  ansible.builtin.command: dnf swap --allowerasing pipewire-pulseaudio pulseaudio

- name: Download greenclip
  become: true
  ansible.builtin.get_url:
    url: https://github.com/erebe/greenclip/releases/download/v4.2/greenclip
    dest: /usr/local/bin/
    mode: u=rwx,g=rx,o=rx

- name: "Install fonts"
  block:
    - name: Ensure fonts folder exists
      ansible.builtin.file:
        path: ~/.fonts
        state: directory
        mode: "775"

    - name: Install jetbrains mono
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/JetBrainsMono.zip
        dest: ~/.fonts
        remote_src: true

    - name: Reset font cache
      ansible.builtin.command: fc-cache -fv
      register: result
      changed_when: result.rc == 0
