- name: Ensure fonts folder exists
  ansible.builtin.file:
    path: ~/.fonts
    state: directory
    mode: "775"

- name: Install jetbrains mono
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/JetBrainsMono.zip
    dest: ~/.fonts
    remote_src: true

- name: Reset font cache
  ansible.builtin.command: fc-cache -fv
  register: result
  changed_when: result.rc == 0
