- name: Download dotfiles
  ansible.builtin.git:
    repo: https://github.com/emillen/Dotfiles.git
    dest: ~/Dotfiles

- name: Get my Dotfiles
  ansible.builtin.shell: |
    cd ~/Dotfiles
    stow -R --adopt .
    git restore .
  register: result
  changed_when: result.rc == 0
