- name: Install neovim from deb pkg
  become: true
  apt:
    deb: https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.deb

- name: Create the nvim autoload directory
  file:
    path: ~/.local/share/nvim/site/autoload/
    state: directory

- name: Install vim-plug in the autoload directory
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
