- name: Cleanup old neovim installation
  file:
    path: ~/.local/share/nvim
    state: absent

- name: Download neovim
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy files to correct location
  become: true
  synchronize:
    src: /tmp/nvim-linux64/
    dest: /usr/

- name: Cleanup
  become: true
  file:
    path: /tmp/nvim-linux64
    state: absent
