- name: Download neovim
  ansible.builtin.unarchive:
    src: https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy the neovim files to the correct location
  become: true
  ansible.builtin.copy:
    src: /tmp/nvim-linux64/
    dest: /usr/local/

- name: Install vim-plug
  shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Remove the tmp folder
  file:
    state: absent
    path: /tmp/nvim-linux64/
