- name: Install tools on debian distros
  when: ansible_os_family == "Debian"
  block:
    - name: Add fish repo
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:fish-shell/release-3
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add fish repo
      become: true
      when: ansible_distribution == "Debian"
      block:
        - name: Download key
          ansible.builtin.get_url:
            url: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key
            dest: /etc/apt/trusted.gpg.d/somerepo.asc
            mode: u=rw,g=r,o=r
        - name: Add repo
          ansible.builtin.apt_repository:
            repo: deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /
            state: present

    - name: Install packages through apt
      when: ansible_os_family  == "Debian"
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          [
            "git",
            "curl",
            "tmux",
            "fzf",
            "zoxide",
            "exa",
            "bat",
            "ripgrep",
            "tldr",
            "nodejs",
            "npm",
            "golang",
            "awscli",
            "fish",
            "fd-find",
            "stow",
            "rsync",
            "jq",
          ]
    - name: Install packages through pacman
      when: ansible_os_family  == "Archlinux"
      become: true
      community.general.pacman:
        name:
          [
            "git",
            "curl",
            "tmux",
            "fzf",
            "zoxide",
            "exa",
            "bat",
            "ripgrep",
            "tldr",
            "nodejs",
            "npm",
            "golang",
            "awscli",
            "fish",
            "fd-find",
            "stow",
            "rsync",
            "jq",
          ]

    - name: Install things through snap
      become: true
      tags: [alacritty]
      ansible.builtin.shell: |
        snap install firefox
        snap install ruby --classic
        snap install kubectl --classic
      when: ansible_distribution == 'Ubuntu'
      register: result
      changed_when: result.rc == 0

    - name: Install things for debian
      become: true
      ansible.builtin.apt:
        update_cache: true
        name: [kubernetes-client, ruby]
      when: ansible_distribution == "Debian"

# For fedora etc
- name: Install tools on dnf distros
  block:
    - name: Install tools through dnf
      become: true
      ansible.builtin.dnf:
        name:
          [
            "git",
            "curl",
            "tmux",
            "fzf",
            "zoxide",
            "exa",
            "bat",
            "ripgrep",
            "tldr",
            "nodejs",
            "npm",
            "golang",
            "awscli",
            "fish",
            "fd-find",
            "stow",
            "rsync",
            "ruby",
            "jq",
          ]
# Thins we can do on all distros
- name: Update nodejs
  become: true
  ansible.builtin.shell: |
    npm install -g n
    n stable
    npm install -g npm@latest
  register: result
  changed_when: result.rc == 0

- name: Get rust
  block:
    - name: Install rustup from source
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: "+x"
      tags: [alacritty]

    - name: Install rustup
      ansible.builtin.command: /tmp/rustup.sh -y
      tags: [alacritty]
      register: result
      changed_when: result.rc == 0

    - name: Install the rust thingies
      tags:
        - alacritty
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
      ansible.builtin.shell: |
        rustup install stable
        rustup default stable
      register: result
      changed_when: result.rc == 0

- name: Download tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
