- name: Add fish repo
  become: true
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present

- name: Install packages through apt
  become: true
  apt:
    update_cache: true
    name:
      [
        "git",
        "i3-wm",
        "i3lock",
        "i3lock-fancy",
        "rofi",
        "polybar",
        "dunst",
        "arandr",
        "autorandr",
        "xdotool",
        "blueman",
        "xbindkeys",
        "curl",
        "tmux",
        "tmuxinator",
        "fzf",
        "zoxide",
        "exa",
        "bat",
        "ripgrep",
        "xclip",
        "tldr",
        "nodejs",
        "npm",
        "golang",
        "redshift",
        "awscli",
        "fish",
        "fd-find",
      ]

- name: install things through snap
  become: true
  shell: |
    snap install firefox
    snap install ruby --classic
    snap install kubectl --classic
    snap install rustup --classic

- name: Install the rust thingies
  shell: |
    rustup install stable
    rustup default stable

- name: download tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: update nodejs
  shell: |
    sudo npm install -g n
    sudo n stable
    sudo npm install -g npm@latest
