- name: Install packages through apt
  become: true
  apt:
    name:
      [
        "git",
        "i3-wm",
        "i3lock",
        "i3lock-fancy",
        "rofi",
        "polybar",
        "dunst",
        "xdotool",
        "blueman",
        "xbindkeys",
        "curl",
        "tmux",
        "fzf",
        "exa",
        "bat",
        "ripgrep",
        "xclip",
        "tldr",
        "nodejs",
        "npm",
        "golang",
      ]

- name: install things through snap
  become: true
  shell: |
    snap install firefox
    snap install ruby --classic
    snap install kubectl --classic
    snap install rustup --classic

- name: Install tmuxinator
  become: true
  shell: |
    gem install tmuxinator
