- name: Add fish repo
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
    state: present

- name: Install packages through apt
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      [
        "git",
        "curl",
        "tmux",
        "fzf",
        "zoxide",
        "exa",
        "bat",
        "ripgrep",
        "tldr",
        "nodejs",
        "npm",
        "golang",
        "awscli",
        "fish",
        "fd-find",
        "stow",
      ]

- name: Install things through snap
  become: true
  ansible.builtin.shell: |
    snap install firefox
    snap install ruby --classic
    snap install kubectl --classic
    snap install rustup --classic

  register: result
  changed_when: result.rc == 0

- name: Install the rust thingies
  tags:
    - alacritty
  ansible.builtin.shell: |
    rustup install stable
    rustup default stable
  register: result
  changed_when: result.rc == 0

- name: Download tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Update nodejs
  ansible.builtin.shell: |
    sudo npm install -g n
    sudo n stable
    sudo npm install -g npm@latest
  register: result
  changed_when: result.rc == 0
