- name: Install packages i need to work
  become: true
  apt:
    name:
      [
        "git",
        "i3-wm",
        "i3lock",
        "i3lock-fancy",
        "rofi",
        "polybar",
        "xdotool",
        "blueman",
        "xbindkeys",
        "tmux",
        "fzf",
        "bat",
        "ripgrep",
        "xclip",
        "tldr",
        "nodejs",
        "npm",
        "golang",
      ]

- name: Install tmuxinator
  become: true
  shell: |
    snap install ruby --classic
    gem install tmuxinator

- name: Install rustup
  become: true
  shell: |
    snap install rustup

- name: Update rust tool chain
  shell: |
    rustup override set stable
    rustup update stable

- name: install firefox
  become: true
  shell: |
    snap install firefox
